config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }

    root to: 'advertisements#index'

    resources :advertisements do
      scope module: 'advertisements' do
        resources :delete_file, only: %i[destroy]
      end
    end

    resources :categories

    namespace :moderations do
      resources :advertisements, only: %i[index show update destroy]
    end

    resources :users
  end
end

app/models/advertisement.rb
# frozen_string_literal: true

class Advertisement < ApplicationRecord
  include AASM

  has_many_attached :files

  belongs_to :category

  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :status, presence: true

  scope :pagination, ->(page) { order(updated_at: :desc).page(page).per(6) }

  aasm(:status) do
    state :draft
    state :pending_review
    state :approved
    state :rejected
    state :published
    state :archived

    event :send_to_review do
      transitions from: :draft, to: :pending_review
    end

    event :approve do
      transitions from: :pending_review, to: :approved
    end

    event :reject do
      transitions from: :pending_review, to: :rejected
    end

    event :publish do
      transitions from: :approved, to: :published
    end

    event :archive do
      transitions to: :archived
    end
  end
end

app/controllers/advertisements/delete_file_controller.rb
# frozen_string_literal: true

module Advertisements
  class DeleteFileController < ApplicationController
    def destroy
      authorize current_advertisement
      current_advertisement.files.find(params[:id]).purge
      redirect_back(fallback_location: advertisements_path)
    end

    private

    def current_advertisement
      Advertisement.find(params[:advertisement_id])
    end
  end
end

app/controllers/advertisements_controller.rb
# frozen_string_literal: true

class AdvertisementsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @q = Advertisement.published.ransack(params[:q])
    @advertisements = @q.result.includes(:category, :user, files_attachments: :blob).pagination(params[:page])
  end

  def show
    @advertisement = Advertisement.find(params[:id])
  end

  def new
    @advertisement = current_user.advertisements.new
    authorize @advertisement
  end

  def create
    @advertisement = current_user.advertisements.new(advertisement_params)

    authorize @advertisement

    @advertisement.status = params[:advertisement][:draft] == '1' ? :draft : :pending_review

    if @advertisement.save
      redirect_to advertisement_path(@advertisement.id), notice: t('.notice')
    else
      render :new
    end
  end

  def edit
    @advertisement = Advertisement.find(params[:id])
    authorize @advertisement
  end

  def update
    @advertisement = Advertisement.find(params[:id])

    authorize @advertisement

    @advertisement.status = params[:advertisement][:draft] == '1' ? :draft : :pending_review

    if @advertisement.update(advertisement_params)
      redirect_to advertisement_path(@advertisement.id), notice: t('.notice')
    else
      render :edit
    end
  end

  def destroy
    @advertisement = Advertisement.find(params[:id])

    authorize @advertisement

    @advertisement.destroy

    redirect_to advertisements_path, notice: t('.notice')
  end

  private

  def advertisement_params
    params.require(:advertisement).permit(:title, :description, :category_id, files: [])
  end
end

app/controllers/moderations/advertisements_controller.rb
# frozen_string_literal: true

module Moderations
  class AdvertisementsController < ApplicationController
    def index
      authorize Advertisement, :moderate?
      @advertisements = Advertisement.pending_review.pagination(params[:page])
    end

    def show
      authorize current_advertisement, :moderate?
      @advertisement = current_advertisement
    end

    def update
      authorize current_advertisement, :moderate?
      current_advertisement.approve!
      redirect_to moderations_advertisements_path
    end

    def destroy
      authorize current_advertisement, :moderate?
      current_advertisement.reject!
      redirect_to moderations_advertisements_path
    end

    private

    def current_advertisement
      Advertisement.find(params[:id])
    end
  end
end

app/views/advertisements/_form.html.slim
= simple_form_for advertisement do |f|
  = f.input :title, input_html: { id: 'title' }, label_html: { for: 'title' }
  = f.input :description
  = f.label :category, class: "mt-2 me-2"
  = f.collection_select :category_id, Category.all, :id, :name
  = f.input :draft?, as: :boolean
  - if advertisement.files.any? { |file| file.id.present? }
    strong
      = t('images')
      ul
      - advertisement.files.each do |file|
        - if file.id.present?
          li
            = cl_image_tag file.key, width: 50, crop: "fill"
            = link_to t('remove'), advertisement_delete_file_path(advertisement.id, file.id), method: :delete, data: { confirm: 'Are you sure?' }
  .field.mb-2
    = f.label :files, class: "me-2"
    = f.file_field :files, multiple: true, accept: 'image/jpg, image/jpeg, image/png, image/gif'
  #preview
  = f.submit t('simple_form.labels.advertisement.submit'), class: "btn btn-primary mt-2"

= javascript_pack_tag 'uploader_preview', 'data-turbolinks-track': 'reload'

app/views/advertisements/_item.html.slim
.card
  - if advertisement.files.any?
    - advertisement.files.each do |file|
      = cl_image_tag file.key, width: 1000, crop: "fill", class: "card-img-top mb-1"
  .card-body
    h5.card-title
      = advertisement.title
    p.card-text
      p = advertisement.description
      p.badge.rounded-pill.bg-secondary = advertisement.category.name
      p = link_to UserPresenter.new(advertisement.user).display_name, user_path(advertisement.user.id)
      p.text-muted
        = t('advertisement.status')
        |  #{advertisement.status.humanize}
      p.text-muted
        = t('advertisement.created_at')
        |  #{advertisement.created_at}
      p.text-muted
        = t('advertisement.updated_at')
        |  #{advertisement.updated_at}
      
    - if policy(advertisement).edit?
      a.btn.btn-outline-primary.me-2[href="#{edit_advertisement_path(advertisement.id)}"]
        = t('advertisement.edit')
    - if policy(advertisement).destroy? && advertisement.published?
      = link_to t('advertisement.destroy'), advertisement_path(advertisement.id), method: :delete, class: "btn btn-outline-danger me-2", data: { confirm: 'Are you sure?' }
    
    - if policy(advertisement).moderate? && advertisement.pending_review?
      = link_to t('advertisement.approve'), moderations_advertisement_path(advertisement.id), class: "btn btn-outline-success me-2", method: :patch
      = link_to t('advertisement.reject'), moderations_advertisement_path(advertisement.id), class: "btn btn-outline-danger me-2", method: :delete

app/views/advertisements/_list.html.slim
.container
  .row 
    - advertisements.each do |advertisement|
      .col-md-4.mb-3
        .card
          - if advertisement.files.any?
            = cl_image_tag advertisement.files.first.key, width: 800, crop: "fill", class: "card-img-top"
          .card-body
            h5.card-title
              = advertisement.title
            p.card-text
              = advertisement.description.truncate(100)
            = link_to "#{advertisement.category.name}", category_path(advertisement.category_id), class: "btn btn-primary"
            p.card-text
              = link_to UserPresenter.new(advertisement.user).display_name, user_path(advertisement.user.id)
            - conditional_advertisement_path = moderation ? moderations_advertisement_path(advertisement.id) : advertisement_path(advertisement.id)
            = link_to t('advertisement.read_more'), conditional_advertisement_path, class: "btn btn-outline-primary"
  .row
    .col-md-12
      = paginate advertisements

app/views/advertisements/edit.html.slim
h1 = t("advertisement.edit_advertisement")

= render "form", advertisement: @advertisement

app/views/advertisements/index.html.slim
#accordionExample.accordion
  .accordion-item
    h2#headingOne.accordion-header
      button.accordion-button.collapsed[type="button" data-bs-toggle="collapse" data-bs-target="#panelsStayOpen-collapseOne" aria-expanded="false" aria-controls="panelsStayOpen-collapseOne"]
        = t('advertisement.search')
    #panelsStayOpen-collapseOne.accordion-collapse.collapse[aria-labelledby="panelsStayOpen-headingOne"]
      .accordion-body
          .row.justify-content-center
            .card.bg-secondary[style="width: 19rem;"]
              ul.list-group
              = search_form_for @q do |f|
                li.list-group-item
                  = f.label t('advertisement.title')
                  = f.search_field :title_cont
                li.list-group-item
                  = f.label t('advertisement.description')
                  = f.search_field :description_cont
                li.list-group-item
                  = f.label t('category.category')
                  = f.collection_select :category_id_eq, Category.all, :id, :name
                li.list-group-item
                  = f.submit
.row.justify-content-center.text-center.mb-2.mt-2
  .col-2.me-1
      = sort_link(@q, :title, t('advertisement.title'))
  .col-2.me-4
      = sort_link(@q, :description, t('advertisement.description')) 
  .col-2.ms-2
      = sort_link(@q, :category_name, t('category.category')) 

= render 'list', advertisements: @advertisements, moderation: false

app/views/advertisements/new.html.slim
h1 = t('advertisement.new_advertisement')

= render "form", advertisement: @advertisement

app/views/advertisements/show.html.slim
= render 'item', advertisement: @advertisement