config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  scope '(:locale)', locale: /en|ru/ do
    devise_for :users, controllers: {
      registrations: 'users/registrations'
    }

    root to: 'advertisements#index'

    resources :advertisements do
      scope module: 'advertisements' do
        resources :delete_file, only: %i[destroy]
      end
    end

    resources :categories

    namespace :moderations do
      resources :advertisements, only: %i[index show update destroy]
    end

    resources :users
  end
end

app/views/layouts/_messages.html.slim
.container
  - flash.each do |name, msg|
    div class=("alert alert-#{name == 'notice' ? 'success' : 'danger'} alert-dismissible fade show") role="alert"
      = msg
      button.btn-close[type="button" data-bs-dismiss="alert" aria-label="Close"]
        span[aria-hidden="true"]

app/views/layouts/_navigation.html.slim
nav.navbar.navbar-expand-lg.navbar-dark.bg-dark.bg-gradient
  .container-fluid
    = link_to t('navigation.back'), :back, class: "btn btn-primary"
    a.navbar-brand.fw-bold.mx-3 href="#{root_path}" ADS APP
    a.nav-link.text-white href="#{categories_path}" = t('navigation.categories')
    button.navbar-toggler aria-controls="navbarScroll" aria-expanded="false" aria-label=("Toggle navigation") data-bs-target="#navbarScroll" data-bs-toggle="collapse" type="button" 
      span.navbar-toggler-icon
    #navbarScroll.collapse.navbar-collapse
      ul.navbar-nav.me-auto.my-2.my-lg-0.navbar-nav-scroll style=("--bs-scroll-height: 100px;") 
      form.d-flex
        ul.navbar-nav
          - if current_user.present?
            li.nav-item.dropdown
              a#navbarScrollingDropdown.nav-link.dropdown-toggle aria-expanded="false" data-bs-toggle="dropdown" href="#" role="button" 
                = UserPresenter.new(current_user).display_name
              ul.dropdown-menu.dropdown-menu-end aria-labelledby="navbarScrollingDropdown" 
                li
                  a.dropdown-item href="#{user_path(current_user.id)}" = t('navigation.profile')
                - if policy(Advertisement).new?
                  li
                    a.dropdown-item href="#{new_advertisement_path}" = t('navigation.create_new_ad')
                - if policy(Advertisement).moderate?
                  li
                    a.dropdown-item href="#{moderations_advertisements_path}" = t('navigation.ads_for_moderation')
                  li
                    a.dropdown-item href="#{users_path}" = t('user.all_users')
                li
                  hr.dropdown-divider
                li
                  = link_to t('navigation.logout'), destroy_user_session_path, class: "dropdown-item", method: :delete
          - else 
            li.nav-item
              = link_to t('navigation.login'), new_user_session_path, class: "nav-link"
            li.nav-item
              = link_to t('navigation.sign_up'), new_user_registration_path, class: "nav-link"
      = link_to 'eng', {locale: :en}, class: "me-2"
      = link_to 'ru', {locale: :ru}, class: "me-2"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | AdsApp
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'layouts/navigation'
    .container.mt-2.mb-5
      = render 'layouts/messages'
      = yield